import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Header from "@/composnents/Header/header";
import { CompanyInfo } from "@/types/schema";
// import MainLoader from "@/composnents/Loaders/MainLoader";
import { TimelineProvider } from "@/context/MainLoaderTimeLine";
import { AnalyticsProvider } from "@/providers/analytic-provider";
import { SectionVisibilityProvider } from "@/composnents/contact/SectionVisibilityContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const dynamic = "force-dynamic";

async function getCompanyInfo(): Promise<CompanyInfo | null> {
  try {
    const res = await fetch(process.env.NEXT_PUBLIC_BACKEND_URL + "api/company-info", {
      cache: "force-cache",
      next: { revalidate: 3600 },
    })
    if (!res.ok) return null
    const json = await res.json()
    return json?.data ?? null
  } catch {
    return null
  }
}

export async function generateMetadata(): Promise<Metadata> {
  const companyInfo = await getCompanyInfo();

  return {

    title: companyInfo?.metaTitle ?? "Create Next App",
    description:
      companyInfo?.metaDescription ?? "Generated by create next app",

    keywords: companyInfo?.metaKeywords
      ? companyInfo.metaKeywords.split(",")
      : [],

    openGraph: {
      type: "website",
      title: companyInfo?.metaTitle,
      description: companyInfo?.metaDescription,
      siteName: companyInfo?.name,
      images: companyInfo?.logo?.url
        ? [
          {
            url: companyInfo.logo.url,
            width: companyInfo.logo.width ?? 1200,
            height: companyInfo.logo.height ?? 630,
            alt: companyInfo.logo.alt ?? companyInfo.name,
          },
        ]
        : [],
      locale: "en_US",
    },

    twitter: {
      card: "summary_large_image",
      title: companyInfo?.metaTitle,
      description: companyInfo?.metaDescription,
      images: companyInfo?.logo?.url
        ? [companyInfo.logo.url]
        : [],
    },

    icons: {
      icon: companyInfo?.logo?.url,
      shortcut: companyInfo?.logo?.url,
      apple: companyInfo?.logo?.url,
    },
    robots: {
      index: true,
      follow: true,
      nocache: false,
      googleBot: {
        index: true,
        follow: true,
        noimageindex: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },

    },

    metadataBase: new URL("http://localhost:3000"),
  };
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnalyticsProvider>
          <TimelineProvider>
            <SectionVisibilityProvider>

              <main>
                {children}
              </main>
            </SectionVisibilityProvider>
          </TimelineProvider>
        </AnalyticsProvider>
      </body>
    </html>
  );
}
