import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TimelineProvider } from "@/context/MainLoaderTimeLine";
import { AnalyticsProvider } from "@/providers/analytic-provider";
import { SectionVisibilityProvider } from "@/composnents/contact/SectionVisibilityContext";
import SmoothScrolling from "@/composnents/scroll/smoothScrolling";
import { getCompanyInfo } from "./(routes)/services/comp/Fetchers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export async function generateMetadata(): Promise<Metadata> {

  const companyInfo = await getCompanyInfo();

  return {
    title: companyInfo?.metaTitle ?? "Create Next App",
    description: companyInfo?.metaDescription ?? "Generated by create next app",
    keywords: companyInfo?.metaKeywords ? companyInfo.metaKeywords.split(",") : [],

    openGraph: {
      type: "website",
      title: companyInfo?.metaTitle ?? "Create Next App",
      description: companyInfo?.metaDescription ?? "Generated by create next app",
      siteName: companyInfo?.name ?? "Create Next App",
      images: companyInfo?.logo?.url
        ? [
            {
              url: companyInfo.logo.url,
              width: companyInfo.logo.width ?? 1200,
              height: companyInfo.logo.height ?? 630,
              alt: companyInfo.logo.alt ?? companyInfo.name,
            },
          ]
        : [],
      locale: "en_US",
    },

    twitter: {
      card: "summary_large_image",
      title: companyInfo?.metaTitle ?? "Create Next App",
      description: companyInfo?.metaDescription ?? "Generated by create next app",
      images: companyInfo?.logo?.url ? [companyInfo.logo.url] : [],
    },

    icons: {
      icon: companyInfo?.logo?.url ?? "/favicon.ico",
      shortcut: companyInfo?.logo?.url ?? "/favicon.ico",
      apple: companyInfo?.logo?.url ?? "/apple-touch-icon.png",
    },

    robots: {
      index: true,
      follow: true,
      nocache: false,
      googleBot: {
        index: true,
        follow: true,
        noimageindex: false,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },

    metadataBase: new URL(
      process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000"
    ),
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnalyticsProvider>
          <TimelineProvider>
            <SectionVisibilityProvider>
              <SmoothScrolling>
                <main>{children}</main>
              </SmoothScrolling>
            </SectionVisibilityProvider>
          </TimelineProvider>
        </AnalyticsProvider>
      </body>
    </html>
  );
}